jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, user-service, restaurant-service, shop-service, hotel-service, notification-service, payment-service]
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker image
      run: |
        docker build -t yourdockerhubusername/${{ matrix.service }}:latest ./${{ matrix.service }}
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push yourdockerhubusername/${{ matrix.service }}:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
