name: Authentication Service CI

on:
  push:
    branches: [main]
    paths:
      - 'authentication-service/**'
  pull_request:
    branches: [main]
    paths:
      - 'authentication-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./authentication-service
          file: ./authentication-service/Dockerfile
          push: true
          tags: yourusername/authentication-service:latest
